# This is Atlassian CI configuration
# Check https://bitbucket-pipelines.atlassian.io/validator for quick information

image: golang:1.8

pipelines:
  default:
    - step:
        script:
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"

          - cd "${PACKAGE_PATH}"
          - export BUILD_COMMIT=${BITBUCKET_COMMIT}
          - export BUILD_BRANCH=${BITBUCKET_BRANCH}
          - make info clean lint gocov-report distr
